
package BakeryManagement.Forms;

import BakeryManagement.Functions.BackupFunctions;
import BakeryManagement.Functions.RetriveFunctions;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



public class Menu extends javax.swing.JFrame {

int xx=0;
int yy=0;

    public Menu() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Drag = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bakeryMGMT = new javax.swing.JButton();
        employeesMGMT = new javax.swing.JButton();
        customerMGMT = new javax.swing.JButton();
        productMGMT = new javax.swing.JButton();
        stockMGMT = new javax.swing.JButton();
        suppliersMGMT = new javax.swing.JButton();
        orderMGMT = new javax.swing.JButton();
        close = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bakery Management System");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        Drag.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 1, 0));
        Drag.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Drag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                DragMouseDragged(evt);
            }
        });
        Drag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DragMousePressed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\314\\Project\\BakeryManagementSystem\\src\\BakeryManagement\\Forms\\Icons\\logo.png")); // NOI18N

        bakeryMGMT.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        bakeryMGMT.setIcon(new javax.swing.ImageIcon("D:\\314\\Project\\BakeryManagementSystem\\src\\BakeryManagement\\Forms\\Icons\\bread-icon.png")); // NOI18N
        bakeryMGMT.setText("Bakery Management  ");
        bakeryMGMT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bakeryMGMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bakeryMGMTActionPerformed(evt);
            }
        });

        employeesMGMT.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        employeesMGMT.setIcon(new javax.swing.ImageIcon("D:\\314\\Project\\BakeryManagementSystem\\src\\BakeryManagement\\Forms\\Icons\\Preppy-icon.png")); // NOI18N
        employeesMGMT.setText("Employees  Management");
        employeesMGMT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        employeesMGMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeesMGMTActionPerformed(evt);
            }
        });

        customerMGMT.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        customerMGMT.setIcon(new javax.swing.ImageIcon("D:\\314\\Project\\BakeryManagementSystem\\src\\BakeryManagement\\Forms\\Icons\\User-Group-icon.png")); // NOI18N
        customerMGMT.setText("Customer Management ");
        customerMGMT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        customerMGMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerMGMTActionPerformed(evt);
            }
        });

        productMGMT.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        productMGMT.setIcon(new javax.swing.ImageIcon("D:\\314\\Project\\BakeryManagementSystem\\src\\BakeryManagement\\Forms\\Icons\\Coffee-brown-icon.png")); // NOI18N
        productMGMT.setText("Product Management");
        productMGMT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productMGMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productMGMTActionPerformed(evt);
            }
        });

        stockMGMT.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        stockMGMT.setIcon(new javax.swing.ImageIcon("D:\\314\\Project\\BakeryManagementSystem\\src\\BakeryManagement\\Forms\\Icons\\inventory-maintenance-icon.png")); // NOI18N
        stockMGMT.setText("Stock Management");
        stockMGMT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        stockMGMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockMGMTActionPerformed(evt);
            }
        });

        suppliersMGMT.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        suppliersMGMT.setIcon(new javax.swing.ImageIcon("D:\\314\\Project\\BakeryManagementSystem\\src\\BakeryManagement\\Forms\\Icons\\42554-delivery-truck-icon.png")); // NOI18N
        suppliersMGMT.setText("Suppliers  Management");
        suppliersMGMT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        suppliersMGMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliersMGMTActionPerformed(evt);
            }
        });

        orderMGMT.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        orderMGMT.setIcon(new javax.swing.ImageIcon("D:\\314\\Project\\BakeryManagementSystem\\src\\BakeryManagement\\Forms\\Icons\\shopping-icon.png")); // NOI18N
        orderMGMT.setText("Order Management");
        orderMGMT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        orderMGMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderMGMTActionPerformed(evt);
            }
        });

        close.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setText("X");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeMousePressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("D:\\314\\Project\\BakeryManagementSystem\\src\\BakeryManagement\\Forms\\Icons\\iconfinder_Upload_132671.png")); // NOI18N
        jButton1.setText("Backup Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("D:\\314\\Project\\BakeryManagementSystem\\src\\BakeryManagement\\Forms\\Icons\\iconfinder_Tune_132605.png")); // NOI18N
        jButton2.setText("retrive Data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Drag, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bakeryMGMT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(customerMGMT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(suppliersMGMT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(orderMGMT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(stockMGMT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(employeesMGMT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(productMGMT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bakeryMGMT, customerMGMT, employeesMGMT, orderMGMT, productMGMT, stockMGMT, suppliersMGMT});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Drag, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bakeryMGMT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(customerMGMT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(employeesMGMT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(productMGMT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(stockMGMT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addComponent(suppliersMGMT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(orderMGMT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1))))
                .addGap(13, 13, 13))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bakeryMGMT, customerMGMT, employeesMGMT, orderMGMT, productMGMT, stockMGMT, suppliersMGMT});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void orderMGMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderMGMTActionPerformed
     new OrderMGMT().show();
    }//GEN-LAST:event_orderMGMTActionPerformed

    private void DragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DragMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_DragMouseDragged

    private void DragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DragMousePressed
        xx=evt.getX();
        yy=evt.getY();
    }//GEN-LAST:event_DragMousePressed

    private void closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMousePressed
    System.exit(0);     
    }//GEN-LAST:event_closeMousePressed

    private void bakeryMGMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bakeryMGMTActionPerformed
    new BakeryMGMT().show();        
    }//GEN-LAST:event_bakeryMGMTActionPerformed

    private void customerMGMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerMGMTActionPerformed
       new CustomerMGMT().show();
    }//GEN-LAST:event_customerMGMTActionPerformed

    private void employeesMGMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeesMGMTActionPerformed
      new EmployeesMGMT().show();
    }//GEN-LAST:event_employeesMGMTActionPerformed

    private void productMGMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productMGMTActionPerformed
      new ProductMGMT().show();
    }//GEN-LAST:event_productMGMTActionPerformed

    private void stockMGMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockMGMTActionPerformed
     new StockMGMT().show();
    }//GEN-LAST:event_stockMGMTActionPerformed

    private void suppliersMGMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliersMGMTActionPerformed
    new SuppliersMGMT().show();
    }//GEN-LAST:event_suppliersMGMTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  
    try {
        RetriveFunctions.retrieve_employee();
        RetriveFunctions.retrieve_order();
        RetriveFunctions.retrieve_orderderived();
        RetriveFunctions.retrieve_product();
        RetriveFunctions.retrieve_stock();
        RetriveFunctions.retrieve_suppliers();
        
        JOptionPane.showMessageDialog(null,"ALL Data Succesfully Retrive");
    } catch (IOException ex) {
        Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
    }
 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    try {
        BackupFunctions.backup_bakery();
        BackupFunctions.backup_customer();
        BackupFunctions.backup_employee();
        BackupFunctions.backup_order();
        BackupFunctions.backup_orderderived();
        BackupFunctions.backup_product();
        BackupFunctions.backup_stock();
        BackupFunctions.backup_suppliers();
        JOptionPane.showMessageDialog(null,"ALL Data Succesfully Backup!");
    } catch (IOException ex) {
        Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
    }
     
    }//GEN-LAST:event_jButton2ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Drag;
    private javax.swing.JButton bakeryMGMT;
    private javax.swing.JLabel close;
    private javax.swing.JButton customerMGMT;
    private javax.swing.JButton employeesMGMT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton orderMGMT;
    private javax.swing.JButton productMGMT;
    private javax.swing.JButton stockMGMT;
    private javax.swing.JButton suppliersMGMT;
    // End of variables declaration//GEN-END:variables
}
